name: Python Test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # GitHub 저장소 코드를 Runner로 가져온다.
      - name: Checkout source code
        uses: actions/checkout@v6
      
      # Python 실행환경을 구성한다.
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      
      # 테스트 도구를 설치한다.
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      # 테스트를 실행한다.
      - name: Run tests
        run: pytest -v